apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs-kubeaction
  namespace: argo-events
spec:
  type: sqs
  sqs:
    kubeaction:
      # jsonBody specifies that all event body payload coming from this
      # source will be JSON
      jsonBody: true
      region: "ap-northeast-2"
      queue: "kubeaction-sqs"
      waitTimeSeconds: 20