apiVersion: kubeaction.spaceone.dev/v1alpha1
kind: EventType
metadata:
  name: webhook-event-sourc
  namespace: argo-events
spec:
  type: webhook
  event_type_name: ci-webhook
  gateway_replica: 1
  sensor_port: 9300
  events:
    intergraion:
      port: 12000
      endpoint: /intergraion
      method: POST