apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flows.kubeaction.spaceone.dev
spec:
  scope: Namespaced
  group: kubeaction.spaceone.dev
  names:
    kind: Flow
    plural: flows
    singular: flow
    shortNames:
      - fls
      - fl
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: events.kubeaction.spaceone.dev
spec:
  scope: Namespaced
  version: v1alpha1
  group: kubeaction.spaceone.dev
  names:
    kind: Event
    plural: events
    singular: event
    shortNames:
      - evs
      - ev
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventtypes.kubeaction.spaceone.dev
spec:
  scope: Namespaced
  version: v1alpha1
  group: kubeaction.spaceone.dev
  names:
    kind: EventType
    plural: eventtypes
    singular: eventtype
    shortNames:
      - evts
      - evt
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tasks.kubeaction.spaceone.dev
spec:
  scope: Namespaced
  version: v1alpha1
  group: kubeaction.spaceone.dev
  names:
    kind: Task
    plural: tasks
    singular: task
    shortNames:
      - tasks
      - task