name: slack-notiy
on:
    watch:
      types: [started]
jobs:
  notiy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Error Server 📦
        id: request
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: 'http://console-api.dev.pyengine.net/identity/domain/list'
          method: post
      - name: Post to Slack
        uses: opspresso/action-slack@master
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          JSON_PATH: ./target/slack_message.json
