name: slack-notiy
on:
  watch:
    types: [started]
jobs:
  notiy:
    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: '#front-end'
          SLACK_COLOR: '#6638B6'
          SLACK_ICON: https://spaceone.console.dev.spaceone.dev/img/brand_logo.c3ef8139.png
          #           SLACK_MESSAGE: '${{ steps.request.outputs.response }}'
          SLACK_MESSAGE: "로컬에서 돌렸어요!!!!"
          SLACK_USERNAME: OpenAction
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
