apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flows.kubeaction.spaceone.dev
spec:
  scope: Namespaced
  group: kubeaction.spaceone.dev
  names:
    kind: flow
    plural: flows
    singular: flow
    shortNames:
      - fls
      - fl
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            name:
              type: string
            meta:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            on:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            jobs:
              type: object
              x-kubernetes-preserve-unknown-fields: true