apiVersion: kubeaction.spaceone.dev/v1alpha1
kind: Flow
metadata:
  name: simple-flow-3
spec:
  events:
    schedule:
      - cron:  '*/1 * * * *'
  jobs:
    first:
      runs-on: ubuntu-latest
      steps:
        - name: let's Run!
          id: request
          run: echo 'test'
        - uses: actions/checkout@v2
