apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: "{name}"
  namespace: "{namespace}"
spec:
  entrypoint: dind-sidecar-example
  templates:
    - name: dind-sidecar-example
      container:
        image: docker:17.10
        command: [sh, -c]
        args: ["until docker ps; do sleep 3; done; docker run --rm debian:latest cat /etc/os-release"]
        env:
          - name: DOCKER_HOST
            value: 127.0.0.1
      sidecars:
        - name: dind
          image: docker:17.10-dind
          securityContext:
            privileged: true
          mirrorVolumeMounts: true